### ISSUE TITLE
Doesn't compile on OF0.8.0

### ISSUE THREAD

**Issue by MuNgLo** [NickHardeman/ofxBullet#21]
Compiling empty example in Code::Blocks under Debian gives..

../../../../addons/ofxBullet/libs/bullet2.8.1/include/BulletMultiThreaded/GpuSoftBodySolvers/DX11/btSoftBodySolverBuffer_DX11.h:19:21: fatal error: windows.h: No such file or directory
 #include <windows.h>

Some compile variable for Bullet that is wrong for Linux environment?

**Comment by NickHardeman** [comment]
Removed the pc specific files. Fixed by https://github.com/NickHardeman/ofxBullet/commit/8a2b3638bba71fe7824fc7a6529aa80eb8ac2741
