### ISSUE TITLE
Doesn't compile with xcode 6

### ISSUE THREAD

**Issue by gdunstone** [NickHardeman/ofxBullet#22]
Bad access in btMatrix3x3.h
breaks on line 360 with bad access EXC_1386_GPFLT.
On oF 0.8.4, Xcode 6.0.1, build for 10.7

**Comment by rom-io** [comment]
same here.
xcode 6.1.1, OSX 10.10.1

**Comment by aknoerig** [comment]
Same here. This error occurs on running any of the examples. Unfortunatelty this happens inside Bullet not ofxBullet, an seems to depend on the chipset (ifdef BT_USE_SSE).
Any clues yet?

I'm on oF master, Xcode 6.1.1, OS X 10.10.2, MacBook Air.
Here's the 

#0	0x00036fbc in btMatrix3x3::getOpenGLSubMatrix(float*) const at /Users/andre/Documents/Code/openFrameworks/addons/ofxBullet/SimpleExample/../../../addons/ofxBullet/libs/bullet2.8.1/include/LinearMath/btMatrix3x3.h:360
#1	0x00036d37 in btTransform::getOpenGLMatrix(float*) const at /Users/andre/Documents/Code/openFrameworks/addons/ofxBullet/SimpleExample/../../../addons/ofxBullet/libs/bullet2.8.1/include/LinearMath/btTransform.h:141
#2	0x00036407 in ofGetOpenGLMatrixFromRigidBody(btRigidBody*, float*) at /Users/andre/Documents/Code/openFrameworks/addons/ofxBullet/src/ofxBulletUtils.h:113
#3	0x00036754 in ofxBulletBaseShape::transformGL() at /Users/andre/Documents/Code/openFrameworks/addons/ofxBullet/src/shapes/ofxBulletBaseShape.cpp:394
#4	0x00039d26 in ofxBulletBox::draw() at /Users/andre/Documents/Code/openFrameworks/addons/ofxBullet/src/shapes/ofxBulletBox.cpp:76
#5	0x00004a79 in testApp::draw() at /Users/andre/Documents/Code/openFrameworks/addons/ofxBullet/SimpleExample/src/testApp.cpp:58
#6	0x000038fd in ofBaseApp::draw(ofEventArgs&) at /Users/andre/Documents/Code/openFrameworks/addons/ofxBullet/SimpleExample/../../../libs/openFrameworks/app/ofBaseApp.h:47
#7	0x00459540 in Poco::PriorityDelegate<ofBaseApp, ofEventArgs, false>::notify(void const*, ofEventArgs&) at /Users/andre/Documents/Code/openFrameworks/libs/openFrameworksCompiled/project/osx/../../../../libs/poco/include/Poco/PriorityDelegate.h:168
#8	0x00430c2a in Poco::PriorityStrategy<ofEventArgs, Poco::AbstractPriorityDelegate<ofEventArgs> >::notify(void const*, ofEventArgs&) [inlined] at /Users/andre/Documents/Code/openFrameworks/libs/openFrameworksCompiled/project/osx/../../../../libs/poco/include/Poco/PriorityStrategy.h:81
#9	0x00430c00 in Poco::AbstractEvent<ofEventArgs, Poco::PriorityStrategy<ofEventArgs, Poco::AbstractPriorityDelegate<ofEventArgs> >, Poco::AbstractPriorityDelegate<ofEventArgs>, Poco::FastMutex>::notify(void const*, ofEventArgs&) at /Users/andre/Documents/Code/openFrameworks/libs/openFrameworksCompiled/project/osx/../../../../libs/poco/include/Poco/AbstractEvent.h:241
#10	0x0042d80d in void ofNotifyEvent<ofEvent<ofEventArgs>, ofEventArgs>(ofEvent<ofEventArgs>&, ofEventArgs&) at /Users/andre/Documents/Code/openFrameworks/libs/openFrameworksCompiled/project/osx/../../../../libs/openFrameworks/events/ofEventUtils.h:172
#11	0x0042cce9 in ofCoreEvents::notifyDraw() at /Users/andre/Documents/Code/openFrameworks/libs/openFrameworks/events/ofEvents.cpp:200
#12	0x00491cc4 in ofAppGLFWWindow::draw() at /Users/andre/Documents/Code/openFrameworks/libs/openFrameworks/app/ofAppGLFWWindow.cpp:328
#13	0x004569ee in ofMainLoop::loopOnce() at /Users/andre/Documents/Code/openFrameworks/libs/openFrameworks/app/ofMainLoop.cpp:124
#14	0x0045691b in ofMainLoop::loop() at /Users/andre/Documents/Code/openFrameworks/libs/openFrameworks/app/ofMainLoop.cpp:106
#15	0x0042b207 in ofRunApp(std::tr1::shared_ptr<ofBaseApp>) at /Users/andre/Documents/Code/openFrameworks/libs/openFrameworks/app/ofAppRunner.cpp:126
#16	0x0042b172 in ofRunApp(ofBaseApp*) at /Users/andre/Documents/Code/openFrameworks/libs/openFrameworks/app/ofAppRunner.cpp:120
#17	0x00002de8 in main at /Users/andre/Documents/Code/openFrameworks/addons/ofxBullet/SimpleExample/src/main.cpp:12
#18	0x00002d75 in start ()

**Comment by aknoerig** [comment]
Looks like this might have been fixed in the bullet 2.82 release (Oct 13) vs 2.81 (Oct 12):
https://github.com/bulletphysics/bullet3/commits/master/src/LinearMath/btMatrix3x3.h

**Comment by NickHardeman** [comment]
I can take a look into this and try compiling all the libs for using 2.82 to fix this issue. However, this will lose support for windows users because of the windows libs.

**Comment by aknoerig** [comment]
This would be great! I'm trying to build them right now, but not successfully yet.
Maybe make a branch for it, so Windows users are not frustrated.

**Comment by NickHardeman** [comment]
I think I will create a release package so windows users can still use the addon. I will try to get around to it in the next couple of days.

**Comment by aknoerig** [comment]
Would love to help, do you have specific instructions somewhere? Bullet compiles fine with Xcode here. Is the rest just a matter of copy/paste/rename?

**Comment by NickHardeman** [comment]
I don't have any instructions posted, but maybe I should. I usually just compile in Release without double precision. And also for iOS. It should just be copying over the libs and the new include .h files. And then testing everything to make sure that nothing has changed.

**Comment by aknoerig** [comment]
Are you using gmake or Xcode? gmake is missing some dependencies here, not sure which ones.

Linking App_HelloWorld
ld: warning: directory not found for option '-L/usr/lib64'
ld: internal error: atom not found in symbolIndex(__ZN20btAlignedObjectArrayIP17btTypedConstraintE17quickSortInternalI33btSortConstraintOnIslandPredicateEEvRKT_ii) for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [../../App_HelloWorld_gmake_x64_release] Error 1
make: *** [App_HelloWorld] Error 2

**Comment by NickHardeman** [comment]
Trying to remember...
I use Cmake to build the XCode projects and then use the XCode project to build the libs I believe.

**Comment by aknoerig** [comment]
That works, but I'm only getting 64bit debug versions, no idea how to set it to also build all the other ones..

**Comment by NickHardeman** [comment]
Using CMAKE, the flag CMAKE_CONFIGURATION_TYPES set to Release might be the answer?

**Comment by aknoerig** [comment]
Seems like this works:

    cd build
    premake_osx xcode4
    xcodebuild -project xcode4/BulletCollision.xcodeproj/ -configuration Release

etc. :)

**Comment by NickHardeman** [comment]
Were you able to build the AllBulletDemos? 
I keep getting this error
duplicate symbol __ZN15DemoApplication20localCreateRigidBodyEfRK11btTransformP16btCollisionShape in:
    /Applications/OpenFrameworks/OF_Addons/ofxBullet/Bullet-src/bullet-2.82-r2704/build-osx/Demos/AllBulletDemos/BULLET_PHYSICS.build/Debug/AppAllBulletDemos.build/Objects-normal/x86_64/BenchmarkDemo.o
    /Applications/OpenFrameworks/OF_Addons/ofxBullet/Bullet-src/bullet-2.82-r2704/build-osx/Demos/OpenGL/Debug/libOpenGLSupport.a(DemoApplication.o)
ld: 1 duplicate symbol for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by NickHardeman** [comment]
I updated the projects to use bullet 2.82. Can you test with the latest master branch and XCode 6?

**Comment by aknoerig** [comment]
Thanks, unfortunately I'm getting the same error in btMatrix3x3 as before. :( This is at runtime, not at compile time. All standard bullet examples are running fine, though.
Could you post your build instructions somewhere, maybe the wiki here? Maybe I need to build the libs on my machine.

**Comment by NickHardeman** [comment]
Are you compiling the 2.82 libs from the google code directory? or the 2.83 libs from github. Im a bit nervous about 2.83 because it is only an alpha. I have just been using the default cmake configuration and then using the generated xcode project to build the libs.

**Comment by aknoerig** [comment]
I did the builds with 2.82 via premake -osx, and had no issues, also all Bullet demos are running fine. Since the original issue persists and I didn't have time to dig deeper, I have now switched to Windows. :) Let me know if I should make a 2.82 windows lib.

**Comment by NickHardeman** [comment]
Have you tried pulling and compiling recently? I put up a couple of patches. @prisonerjohn compiled libs for pc and made some VS2012 projects

**Comment by aknoerig** [comment]
Thanks! Commit 8a2b3638bba71fe7824fc7a6529aa80eb8ac274 actually fixed it. :)
I also submitted a pull request already on a few other things. Consider this one closed!

**Comment by NickHardeman** [comment]
Great!
